### ISSUE TITLE
test data format

### ISSUE THREAD

**Issue by xilinniao123** [jeisner/erma#2]
hi
thanks for sharing!i want to ask the predict process, when predict,first translate the test.txt into test.ff,and the test.txt contains all the column as the train.txt,including the target tag. 
my problem is that if the test file do not contain the target tag,how to test when using the erma trained model,thanks

**Comment by jeisner** [comment]
You should probably use Pacaya instead.  It is a more recent library that includes ERMA training.
https://github.com/mgormley/pacaya

**Comment by mgormley** [comment]
I'll second that: Pacaya also happens to be about 10x faster (just because of a more careful implementation) than this library.

To answer your question: You can always just fill the test file with dummy tags.
